---
environment_name: dev

# Nginx Unit flask settings
flask_branch: v0.0.1

# Prosumer repo settings
rupert_prosumer_branch: v0.0.1

# Rupert Audio Player
rupert_audio_player_branch: v0.0.1

# Settings Config
## Kafka settings config
kafka_bootstrap_servers: "192.168.1.230:9092"
kafka_topics:
  audio_dev: audio.dev
  devices_dev: devices.dev
kafka_consumer_group_id: rupert
kafka_auto_offset_reset: smallest